:twisted_rightwards_arrows: Dataset parser (clean)
galyfray/CVRP pull request #18
Opened 2022-11-21 12:20 UTC by Axelvel

2022-11-21 16:39 UTC, galyfray requested changes
An overall good request. I note that all of your code constantly use single quote, while the rest of the codebase use double quotes. This isn't much of a problem, just noting. 
The description of the PR needs to be improved also.  Please add more detail over what you have done, what you did not do. Include the possible problems or things that will have to be done. Please also provide a copy of the table provided by the make coverage command so that everyone can see how much the tests are effective quickly. Note that you will have to do slight adjustment to the table for it to be recognized as a Markdown table :).

2022-11-21 16:39 UTC, galyfray commented on src/server/utils/utils.py
> +                distance_matrix[node-1][next_node-1] = dist
I think that either the nodes have to be offsetted when reading or the offset should be parametrized. This issue has already been discussed, but nothing was decided about what to do.

2022-11-21 16:39 UTC, galyfray commented on test/server/test_utils.py
> +    'NODES': {1: (145, 215), 2: (151, 264), 3: (159, 261), 4: (130, 254), 5: (200, 176)},
Nodes and cities are duplicated. 
A possible fix could be :
```suggestion
    'NODES': cities,
```

2022-11-21 16:39 UTC, galyfray commented on test/server/test_utils.py
> +distance_matrix = [
Not a big fan of this matrix. Pytest has a way to assert that numbers are close enough.

2022-11-21 16:39 UTC, galyfray commented on test/server/test_utils.py
> +
They should not be any blank lines betweens function's docstring and the function's code. (replacing pydocstyle once again.

2022-11-21 16:39 UTC, galyfray commented on test/server/test_utils.py
> +    # assert evrp.get_towns() == [2, 3]  # TODO: Fix get_towns()
This should be indicated in the PR

2022-11-21 16:40 UTC, galyfray commented
I have also noted that some issue raised by the codacy's code analysis can be fixed.

2022-11-22 21:48 UTC, galyfray requested changes
Great work ! The automatic analysis found some small problems which can be fixed (at least a missing type hint, but I didn't get through every note left by the tool). 
I also reviewed the check that mostly fail because of bad documentation, which has been fixed in another branch.

2022-11-22 21:48 UTC, galyfray commented on src/server/utils/utils.py
> +                distance_matrix[next_node][node] = distance_matrix[node][next_node]
Since you iterate on the whole matrix you should not need this.

2022-11-22 21:48 UTC, galyfray commented on src/__init__.py
> +"""Python package"""
```suggestion
"""Python package."""
```

2022-11-22 21:48 UTC, galyfray commented on src/server/__init__.py
> +"""Python package"""
```suggestion
"""Python package."""
```

2022-11-22 21:56 UTC, galyfray approved these changes
Everything seems fine

2022-11-22 22:01 UTC, galyfray approved these changes

2022-11-22 22:17 UTC, Nexowo approved these changes
Seems to be good, didn't notice any obvious mistake

2022-11-22 22:27 UTC, merged