Linters for uniform code
galyfray/CVRP pull request #3
Opened 2022-09-19 20:23 UTC by galyfray

Added tools to lint the code to ensure both quality and style consistency across all of us.
 - bandit : this tool checks for security issue.
 - pylint & flake8 helps ensure that the code style  respect the PEP8 and will enlighten small mistakes that could escape us.
 - pydocstyle will check that the documentation is present and is conform to the PEP257. It doesn't check for documentation quality.
 All of these tools have their own output (sadly) : 
- bandit.html
- pylint.txt
- flake8.txt
- pydocstyle.txt

A make command has been created to automatically lint : `make lint`

As a side note any python IDE should provide either in a native form or as a plugin an integrated PEP8 checker making most of the heavy lifting.

I would have liked to have the time to condense all of these outputs in a nice HTML page but I have decided to put this out of scope of this PR. 

Bandit, flake8 and pydocstyle's configurations are finalized and only require validation. However the pylint's configuration require more in depth discussion  as this tool offer functionality that goes further than the usual python conventions.

To be able to get the whole picture I added codacy's tracker which include all (and a bit more) of the tools I listed and should (hopefully) provide information directly in GitHub making PR reviewing easier. It also include some other nice features already used in the CI branch.

Be sure to use `make update` if you already have initialized your development environment.

2022-09-20 15:19 UTC, Nexowo commented
Menfou palu

2022-09-20 15:32 UTC, m-aspro requested changes
Good job!

2022-09-20 15:32 UTC, m-aspro commented on Makefile
>  help:
It doesn't work any more on Windows.
Please, fix the command "make help".
Thanks

2022-09-21 19:52 UTC, Nexowo commented
English mistakes and typing errors on make help
depencies -> dependencies
commads -> commands
compleate -> complete

2022-09-24 12:07 UTC, galyfray commented
Due to the discovery of a major bug I have decided to make this PR a draft until everything works fine.

2022-10-01 09:37 UTC, KwassiSenam commented
that's good !!

2022-10-01 09:45 UTC, KwassiSenam reviewed
I've seen all changes.

2022-10-01 09:47 UTC, KwassiSenam commented
Sorry! I'll let Cyril close this PR if everything is ok.

2022-10-02 15:31 UTC, Nexowo approved these changes

2022-10-02 18:59 UTC, m-aspro approved these changes
Tested 2 days ago on my Windows environment and approved.
Good job!

2022-10-03 16:56 UTC, Axelvel approved these changes

2022-10-04 06:04 UTC, merged