GA's main skeleton
galyfray/CVRP pull request #6
Opened 2022-11-07 07:57 UTC by galyfray

## What has been done
 - Implementation of the `ConstraintValidator` Interface
   - Added all the constraint I thought of.
 - Implementation of the Individual Abstract Class
   - Added the `ECVRPSolution` class with the following method implemented : 
     - get_instance
     - get_points
     - get_roads
     - get_fitness
     - is_valid
     - \_\_copy__
 - Added the `ECVRPInstance` class to holds most of the information
 -  Created tests for the various class and methods added

## What has not been done
 - The mutation and crossover methods were not done
 - The GA class itself
 - The system in charge of reading the benchmarks
   - should be part of the server
 The main reasons behind the unimplemented functionality are : 
 - I wanted to keep this PR in a manageable size.
 - I wanted to end this PR before the next sprint cycle. 

## Coverage
|Name  |  Stmts |  Miss | Cover  |
|-|-|-|-|
|||||
|TOTAL |    256  |    0 |  100%|

With 100% coverage and no red flag showed by the linters, I think this PR is up to the standard.

2022-11-07 08:03 UTC, galyfray commented
the `Python application / build` failed because he couldn't update PIP ...

2022-11-08 11:04 UTC, Nexowo submitted a review, later dismissed

2022-11-08 12:15 UTC, galyfray commented on src/cvrp/constraints_validators.py
> +    """ Class in charge of checking the battery capacity is never exeded
done

2022-11-08 12:27 UTC, galyfray commented on src/cvrp/ecvrp.py
> +        self._roads = None
done

2022-11-08 12:27 UTC, galyfray commented on src/cvrp/ecvrp.py
> +        self._fitness = None
done

2022-11-08 12:53 UTC, m-aspro requested changes
Good job! 
Just a little point to modify.

2022-11-08 13:40 UTC, Axelvel commented on src/cvrp/constraints_validators.py
> +    Class in charge of checking if the battery capacity is never exeded
Typo in the docstring. 
```suggestion
    Class in charge of checking if the battery capacity is never exceded
```

2022-11-08 13:41 UTC, galyfray commented
> Good job! Just a little point to modify.

Thanks. But, you did not mention what should be changed in your review.

2022-11-08 13:55 UTC, m-aspro commented on src/cvrp/constraints_validators.py
> +    Class in charge of checking if the battery capacity is never exeded
Could you specify about TW ? 
I mean by adding a comment which explain that is also a time window validator.
Thanks!

2022-11-08 13:58 UTC, m-aspro commented
I added a comment by quoting the line, I think it has been skipped or cancel by error. 
I'll do it again right away, sorry for that! :)

2022-11-08 15:29 UTC, m-aspro commented on src/cvrp/constraints_validators.py
> +    Class in charge of checking if the battery capacity is never exeded
Oh you added it just after we discuss, so it's okay for me, I see no problem

2022-11-08 15:29 UTC, m-aspro approved these changes

2022-11-08 20:10 UTC, KwassiSenam approved these changes

2022-11-08 20:14 UTC, merged